---
- name: Optimize Ubuntu 22.04 VPS and Upgrade to Latest Point Release
  hosts: all
  user: root
  vars:
    ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no' #Disable check for new hosts
    logs2ram_size: 50M
    default_sources_list: |
      deb http://archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
      deb http://archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
      deb http://archive.ubuntu.com/ubuntu jammy-security main restricted universe multiverse

    unnecessary_services:
      - apparmor
      - ModemManager
      - polkit
      - udisks2
      - thermald
      - gpu-manager

  tasks:
    - name: Replace sources.list with default Ubuntu repositories
      copy:
        content: "{{ default_sources_list }}"
        dest: /etc/apt/sources.list
        backup: yes

    - name: Disable provider-specific repositories
      command: rm -f /etc/apt/sources.list.d/*

    - name: Disable unnecessary services
      systemd:
        name: "{{ item }}"
        state: stopped
        enabled: no
      loop: "{{ unnecessary_services }}"

#TIME

    - name: Ensure the system timezone is set to UTC
      ansible.builtin.timezone:
        name: Etc/UTC
        
    - name: Ensure chrony (NTP) package is installed
      apt:
        name: chrony
        state: present

    - name: Ensure chrony service is enabled and running
      service:
        name: chronyd
        state: started
        enabled: true

    - name: Force an immediate synchronization of the time
      command:
        cmd: chronyc makestep
      changed_when: false

    - name: Check if NTP is synchronized
      command: chronyc tracking
      register: ntp_status
      changed_when: false

    - name: Display NTP synchronization status
      debug:
        var: ntp_status.stdout_lines

#LIMITS
    - name: Increase max FD limit / ulimit
      blockinfile:
        path: "/etc/security/limits.conf"
        block: |
          * soft     nproc          1048576
          * hard     nproc          1048576
          * soft     nofile         1048576
          * hard     nofile         1048576
          root soft     nproc          unlimited
          root hard     nproc          unlimited
          root soft     nofile         unlimited
          root hard     nofile         unlimited

    - name: Add sysctl.conf parameters
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        sysctl_set: yes
        reload: yes
      loop:
        - { name: 'vm.min_free_kbytes', value: '131072' } #128Mb Memory Reserve
        - { name: 'vm.swappiness', value: '0' }
        - { name: 'fs.inotify.max_queued_events', value: '1048576' }
        - { name: 'fs.inotify.max_user_instances', value: '1048576' }
        - { name: 'fs.inotify.max_user_watches', value: '1048576' }
        - { name: 'vm.max_map_count', value: '1000000' }
        - { name: 'fs.aio-max-nr', value: '524288' }


#APT
    - name: Remove unnecessary packages
      apt:
        name:
          - irqbalance
          - snapd
          - cups
          - popularity-contest
          - landscape-common
          - postfix
          - sendmail
          - network-manager
          - telnetd
          - xserver-xorg-core
          - xserver-common
          - x11-common
        state: absent
        purge: yes

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install linux-generic-hwe-22.04
      ansible.builtin.apt:
        name: linux-generic-hwe-22.04
        state: present

    - name: Reboot the server
      reboot:

    - name: Update and upgrade all packages
      apt:
        upgrade: dist
        update_cache: yes
        autoclean: yes
        autoremove: yes
      environment:
        DEBIAN_FRONTEND: noninteractive
      tags: upgrade

    - name: Remove swap entry from fstab
      lineinfile:
        path: /etc/fstab
        regexp: '^/swap'
        state: absent

    - name: Install logs2ram dependencies
      apt:
        name: git
        state: present

    - name: Clone logs2ram repository
      git:
        repo: https://github.com/azlux/log2ram.git
        dest: /opt/log2ram

    - name: Install logs2ram
      command: /opt/log2ram/install.sh "{{ logs2ram_size }}"

    - name: Reboot the server
      reboot:

    - name: Clear temporary files
      command: |
        rm -rf /tmp/*
        rm -rf /var/tmp/*

    - name: Purge unused locales
      command: locale-gen --purge

    - name: Clean up apt cache
      apt:
        autoclean: yes
        autoremove: yes
      environment:
        DEBIAN_FRONTEND: noninteractive
